// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package commet

import (
	"context"
	"fmt"
)

type ListFeaturesParams struct {
	CustomerID string `json:"customer_id"`
}

type GetFeatureAccessParams struct {
	CustomerID string  `json:"customer_id"`
	Action     *string `json:"action,omitempty"`
}

type CanUseFeatureParams struct {
	CustomerID string `json:"customer_id"`
}

type CreateFeatureParams struct {
	Name           string      `json:"name"`
	Code           string      `json:"code"`
	Type           FeatureType `json:"type"`
	Description    *string     `json:"description,omitempty"`
	UnitName       *string     `json:"unit_name,omitempty"`
	IdempotencyKey string      `json:"-"`
}

type UpdateFeatureParams struct {
	Name           *string `json:"name,omitempty"`
	Description    *string `json:"description,omitempty"`
	UnitName       *string `json:"unit_name,omitempty"`
	IdempotencyKey string  `json:"-"`
}

type FeaturesResource struct {
	http *httpClient
}

// List all features for a customer's active subscription.
func (r *FeaturesResource) List(ctx context.Context, params *ListFeaturesParams) (*ApiResponse[[]FeatureAccess], error) {
	query := map[string]string{}
	if params.CustomerID != "" {
		query["customer_id"] = params.CustomerID
	}
	return parseResponse[[]FeatureAccess](r.http.get(ctx, "/features", query))
}

// Get feature access details. Use action=canUse to check if customer can consume one more unit.
func (r *FeaturesResource) Get(ctx context.Context, code string, params *GetFeatureAccessParams) (*ApiResponse[FeatureLookup], error) {
	query := map[string]string{}
	if params.CustomerID != "" {
		query["customer_id"] = params.CustomerID
	}
	if params.Action != nil {
		query["action"] = *params.Action
	}
	return parseResponse[FeatureLookup](r.http.get(ctx, fmt.Sprintf("/features/%s", code), query))
}

// Get feature access details. Use action=canUse to check if customer can consume one more unit.
func (r *FeaturesResource) CanUse(ctx context.Context, code string, params *CanUseFeatureParams) (*ApiResponse[FeatureLookup], error) {
	query := map[string]string{}
	query["action"] = "canUse"
	if params.CustomerID != "" {
		query["customer_id"] = params.CustomerID
	}
	return parseResponse[FeatureLookup](r.http.get(ctx, fmt.Sprintf("/features/%s", code), query))
}

// Create a new feature. Code must be lowercase alphanumeric with underscores.
func (r *FeaturesResource) Create(ctx context.Context, params *CreateFeatureParams) (*ApiResponse[Feature], error) {
	body := buildBody(map[string]any{
		"name":        params.Name,
		"code":        params.Code,
		"type":        params.Type,
		"description": params.Description,
		"unit_name":   params.UnitName,
	})
	return parseResponse[Feature](r.http.post(ctx, "/features/manage", body, params.IdempotencyKey))
}

// Update a feature's name, description, or unit name. At least one field must be provided.
func (r *FeaturesResource) Update(ctx context.Context, code string, params *UpdateFeatureParams) (*ApiResponse[Feature], error) {
	body := buildBody(map[string]any{
		"name":        params.Name,
		"description": params.Description,
		"unit_name":   params.UnitName,
	})
	return parseResponse[Feature](r.http.put(ctx, fmt.Sprintf("/features/%s/manage", code), body, params.IdempotencyKey))
}

// Delete a feature. Fails if the feature is attached to active plans or has an active add-on.
func (r *FeaturesResource) Delete(ctx context.Context, code string) (*ApiResponse[DeletedObject], error) {
	return parseResponse[DeletedObject](r.http.delete(ctx, fmt.Sprintf("/features/%s/manage", code), nil, ""))
}
