// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package commet

type generatedResources struct {
	Addons        *AddonsResource
	ApiKeys       *ApiKeysResource
	CreditPacks   *CreditPacksResource
	Customers     *CustomersResource
	Features      *FeaturesResource
	Invoices      *InvoicesResource
	Payouts       *PayoutsResource
	PlanGroups    *PlanGroupsResource
	Plans         *PlansResource
	Portal        *PortalResource
	PromoCodes    *PromoCodesResource
	Quota         *QuotaResource
	Seats         *SeatsResource
	Subscriptions *SubscriptionsResource
	TestClock     *TestClockResource
	Transactions  *TransactionsResource
}

func (r *generatedResources) wireResources(h *httpClient) {
	r.Addons = &AddonsResource{http: h}
	r.ApiKeys = &ApiKeysResource{http: h}
	r.CreditPacks = &CreditPacksResource{http: h}
	r.Customers = &CustomersResource{http: h}
	r.Features = &FeaturesResource{http: h}
	r.Invoices = &InvoicesResource{http: h}
	r.Payouts = &PayoutsResource{http: h}
	r.PlanGroups = &PlanGroupsResource{http: h}
	r.Plans = &PlansResource{http: h}
	r.Portal = &PortalResource{http: h}
	r.PromoCodes = &PromoCodesResource{http: h}
	r.Quota = &QuotaResource{http: h}
	r.Seats = &SeatsResource{http: h}
	r.Subscriptions = &SubscriptionsResource{http: h}
	r.TestClock = &TestClockResource{http: h}
	r.Transactions = &TransactionsResource{http: h}
}
