// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package commet

import (
	"context"
	"fmt"
)

type ListInvoicesParams struct {
	CustomerID     *string `json:"customer_id,omitempty"`
	Status         *string `json:"status,omitempty"`
	SubscriptionID *string `json:"subscription_id,omitempty"`
	Cursor         *string `json:"cursor,omitempty"`
	Limit          *int    `json:"limit,omitempty"`
}

type CreateAdjustmentInvoiceParams struct {
	CustomerID     string         `json:"customer_id"`
	Amount         int            `json:"amount"`
	Description    string         `json:"description"`
	Metadata       map[string]any `json:"metadata,omitempty"`
	IdempotencyKey string         `json:"-"`
}

type SendInvoiceParams struct {
	IdempotencyKey string `json:"-"`
}

type UpdateInvoiceStatusParams struct {
	Status         string `json:"status"`
	IdempotencyKey string `json:"-"`
}

type InvoicesResource struct {
	http *httpClient
}

// List invoices with cursor-based pagination. Filter by customer, status, or subscription.
func (r *InvoicesResource) List(ctx context.Context, params *ListInvoicesParams) (*ApiResponse[[]Invoice], error) {
	query := map[string]string{}
	if params.CustomerID != nil {
		query["customer_id"] = *params.CustomerID
	}
	if params.Status != nil {
		query["status"] = *params.Status
	}
	if params.SubscriptionID != nil {
		query["subscription_id"] = *params.SubscriptionID
	}
	if params.Cursor != nil {
		query["cursor"] = *params.Cursor
	}
	if params.Limit != nil {
		query["limit"] = fmt.Sprintf("%d", *params.Limit)
	}
	return parseResponse[[]Invoice](r.http.get(ctx, "/invoices", query))
}

// Retrieve a single invoice by its public ID, including line items.
func (r *InvoicesResource) Get(ctx context.Context, id string) (*ApiResponse[Invoice], error) {
	return parseResponse[Invoice](r.http.get(ctx, fmt.Sprintf("/invoices/%s", id), nil))
}

// Create a one-off adjustment invoice. Use a negative amount for a credit.
func (r *InvoicesResource) CreateAdjustment(ctx context.Context, params *CreateAdjustmentInvoiceParams) (*ApiResponse[CreatedInvoice], error) {
	body := buildBody(map[string]any{
		"customer_id": params.CustomerID,
		"amount":      params.Amount,
		"description": params.Description,
		"metadata":    params.Metadata,
	})
	return parseResponse[CreatedInvoice](r.http.post(ctx, "/invoices", body, params.IdempotencyKey))
}

// Generate a signed URL to download the invoice as a PDF. The URL expires after 7 days.
func (r *InvoicesResource) GetDownloadURL(ctx context.Context, id string) (*ApiResponse[InvoiceDownload], error) {
	return parseResponse[InvoiceDownload](r.http.get(ctx, fmt.Sprintf("/invoices/%s/download", id), nil))
}

// Send the invoice to the customer via email.
func (r *InvoicesResource) Send(ctx context.Context, id string, params *SendInvoiceParams) (*ApiResponse[SentInvoice], error) {
	return parseResponse[SentInvoice](r.http.post(ctx, fmt.Sprintf("/invoices/%s/send", id), map[string]any{}, params.IdempotencyKey))
}

// Mark an outstanding invoice as "paid" or "void". Cannot change the status of already paid or voided invoices.
func (r *InvoicesResource) UpdateStatus(ctx context.Context, id string, params *UpdateInvoiceStatusParams) (*ApiResponse[InvoiceStatus], error) {
	body := buildBody(map[string]any{
		"status": params.Status,
	})
	return parseResponse[InvoiceStatus](r.http.put(ctx, fmt.Sprintf("/invoices/%s/status", id), body, params.IdempotencyKey))
}
