// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package commet

import (
	"context"
	"fmt"
)

type ListPlansParams struct {
	IncludePrivate *string `json:"include_private,omitempty"`
}

type CreatePlanParams struct {
	Name              string            `json:"name"`
	Code              string            `json:"code"`
	Description       *string           `json:"description,omitempty"`
	ConsumptionModel  *ConsumptionModel `json:"consumption_model,omitempty"`
	IsPublic          *bool             `json:"is_public,omitempty"`
	IsFree            *bool             `json:"is_free,omitempty"`
	BlockOnExhaustion *bool             `json:"block_on_exhaustion,omitempty"`
	PlanGroupID       *string           `json:"plan_group_id,omitempty"`
	Metadata          map[string]any    `json:"metadata,omitempty"`
	IdempotencyKey    string            `json:"-"`
}

type UpdatePlanParams struct {
	Name           *string        `json:"name,omitempty"`
	Description    *string        `json:"description,omitempty"`
	Metadata       map[string]any `json:"metadata,omitempty"`
	IsPublic       *bool          `json:"is_public,omitempty"`
	IdempotencyKey string         `json:"-"`
}

type SetPlanVisibilityParams struct {
	IsPublic       bool   `json:"is_public"`
	IdempotencyKey string `json:"-"`
}

type AddPlanFeatureParams struct {
	FeatureID      string                       `json:"feature_id"`
	Enabled        *bool                        `json:"enabled,omitempty"`
	IncludedAmount *int                         `json:"included_amount,omitempty"`
	Unlimited      *bool                        `json:"unlimited,omitempty"`
	Overage        *AddPlanFeatureParamsOverage `json:"overage,omitempty"`
	CreditsPerUnit *int                         `json:"credits_per_unit,omitempty"`
	PricingMode    *string                      `json:"pricing_mode,omitempty"`
	Margin         *int                         `json:"margin,omitempty"`
	IdempotencyKey string                       `json:"-"`
}

type UpdatePlanFeatureParams struct {
	Enabled        *bool                           `json:"enabled,omitempty"`
	IncludedAmount *int                            `json:"included_amount,omitempty"`
	Unlimited      *bool                           `json:"unlimited,omitempty"`
	Overage        *UpdatePlanFeatureParamsOverage `json:"overage,omitempty"`
	CreditsPerUnit *int                            `json:"credits_per_unit,omitempty"`
	IdempotencyKey string                          `json:"-"`
}

type AddPlanPriceParams struct {
	BillingInterval BillingInterval               `json:"billing_interval"`
	Price           int                           `json:"price"`
	TrialDays       *int                          `json:"trial_days,omitempty"`
	IsDefault       *bool                         `json:"is_default,omitempty"`
	IncludedBalance *int                          `json:"included_balance,omitempty"`
	IncludedCredits *int                          `json:"included_credits,omitempty"`
	IntroOffer      *AddPlanPriceParamsIntroOffer `json:"intro_offer,omitempty"`
	IdempotencyKey  string                        `json:"-"`
}

type UpdatePlanPriceParams struct {
	Price           *int                             `json:"price,omitempty"`
	IsDefault       *bool                            `json:"is_default,omitempty"`
	TrialDays       *int                             `json:"trial_days,omitempty"`
	IncludedBalance *int                             `json:"included_balance,omitempty"`
	IncludedCredits *int                             `json:"included_credits,omitempty"`
	IntroOffer      *UpdatePlanPriceParamsIntroOffer `json:"intro_offer,omitempty"`
	IdempotencyKey  string                           `json:"-"`
}

type SetDefaultPlanPriceParams struct {
	IdempotencyKey string `json:"-"`
}

type UpsertRegionalPricesParams struct {
	Overrides      []UpsertRegionalPricesParamsOverridesItem `json:"overrides"`
	IdempotencyKey string                                    `json:"-"`
}

type SetPlanRegionalPricingParams struct {
	Currency       string                                        `json:"currency"`
	ExchangeRate   float64                                       `json:"exchange_rate"`
	Prices         []SetPlanRegionalPricingParamsPricesItem      `json:"prices,omitempty"`
	Features       []SetPlanRegionalPricingParamsFeaturesItem    `json:"features,omitempty"`
	IntroOffers    []SetPlanRegionalPricingParamsIntroOffersItem `json:"intro_offers,omitempty"`
	IdempotencyKey string                                        `json:"-"`
}

type PlansResource struct {
	http *httpClient
}

// List all plans with their prices and features. Optionally include private plans.
func (r *PlansResource) List(ctx context.Context, params *ListPlansParams) (*ApiResponse[[]Plan], error) {
	query := map[string]string{}
	if params.IncludePrivate != nil {
		query["include_private"] = *params.IncludePrivate
	}
	return parseResponse[[]Plan](r.http.get(ctx, "/plans", query))
}

// Get detailed plan information by code or ID.
func (r *PlansResource) Get(ctx context.Context, id string) (*ApiResponse[Plan], error) {
	return parseResponse[Plan](r.http.get(ctx, fmt.Sprintf("/plans/%s", id), nil))
}

// Create a new plan with optional consumption model, visibility, and plan group assignment.
func (r *PlansResource) Create(ctx context.Context, params *CreatePlanParams) (*ApiResponse[Plan], error) {
	body := buildBody(map[string]any{
		"name":                params.Name,
		"code":                params.Code,
		"description":         params.Description,
		"consumption_model":   params.ConsumptionModel,
		"is_public":           params.IsPublic,
		"is_free":             params.IsFree,
		"block_on_exhaustion": params.BlockOnExhaustion,
		"plan_group_id":       params.PlanGroupID,
		"metadata":            params.Metadata,
	})
	return parseResponse[Plan](r.http.post(ctx, "/plans/manage", body, params.IdempotencyKey))
}

// Update a plan's name, description, visibility, or metadata.
func (r *PlansResource) Update(ctx context.Context, id string, params *UpdatePlanParams) (*ApiResponse[Plan], error) {
	body := buildBody(map[string]any{
		"name":        params.Name,
		"description": params.Description,
		"metadata":    params.Metadata,
		"is_public":   params.IsPublic,
	})
	return parseResponse[Plan](r.http.put(ctx, fmt.Sprintf("/plans/%s/manage", id), body, params.IdempotencyKey))
}

// Soft-delete a plan.
func (r *PlansResource) Delete(ctx context.Context, id string) (*ApiResponse[DeletedObject], error) {
	return parseResponse[DeletedObject](r.http.delete(ctx, fmt.Sprintf("/plans/%s/manage", id), nil, ""))
}

// Toggle a plan between public and private.
func (r *PlansResource) SetVisibility(ctx context.Context, id string, params *SetPlanVisibilityParams) (*ApiResponse[PlanVisibility], error) {
	body := buildBody(map[string]any{
		"is_public": params.IsPublic,
	})
	return parseResponse[PlanVisibility](r.http.put(ctx, fmt.Sprintf("/plans/%s/visibility", id), body, params.IdempotencyKey))
}

// Attach a feature to a plan with limits, overage, and credits configuration.
func (r *PlansResource) AddFeature(ctx context.Context, id string, params *AddPlanFeatureParams) (*ApiResponse[PlanFeature], error) {
	body := buildBody(map[string]any{
		"feature_id":       params.FeatureID,
		"enabled":          params.Enabled,
		"included_amount":  params.IncludedAmount,
		"unlimited":        params.Unlimited,
		"overage":          params.Overage,
		"credits_per_unit": params.CreditsPerUnit,
		"pricing_mode":     params.PricingMode,
		"margin":           params.Margin,
	})
	return parseResponse[PlanFeature](r.http.post(ctx, fmt.Sprintf("/plans/%s/features", id), body, params.IdempotencyKey))
}

// Update limits, overage, or enabled status of a feature on a plan.
func (r *PlansResource) UpdateFeature(ctx context.Context, id string, featureID string, params *UpdatePlanFeatureParams) (*ApiResponse[PlanFeature], error) {
	body := buildBody(map[string]any{
		"enabled":          params.Enabled,
		"included_amount":  params.IncludedAmount,
		"unlimited":        params.Unlimited,
		"overage":          params.Overage,
		"credits_per_unit": params.CreditsPerUnit,
	})
	return parseResponse[PlanFeature](r.http.put(ctx, fmt.Sprintf("/plans/%s/features/%s", id, featureID), body, params.IdempotencyKey))
}

// Detach a feature from a plan.
func (r *PlansResource) RemoveFeature(ctx context.Context, id string, featureID string) (*ApiResponse[RemovedPlanFeature], error) {
	return parseResponse[RemovedPlanFeature](r.http.delete(ctx, fmt.Sprintf("/plans/%s/features/%s", id, featureID), nil, ""))
}

// Add a billing interval price to a plan with optional trial days and included balance/credits.
func (r *PlansResource) AddPrice(ctx context.Context, id string, params *AddPlanPriceParams) (*ApiResponse[PlanPrice], error) {
	body := buildBody(map[string]any{
		"billing_interval": params.BillingInterval,
		"price":            params.Price,
		"trial_days":       params.TrialDays,
		"is_default":       params.IsDefault,
		"included_balance": params.IncludedBalance,
		"included_credits": params.IncludedCredits,
		"intro_offer":      params.IntroOffer,
	})
	return parseResponse[PlanPrice](r.http.post(ctx, fmt.Sprintf("/plans/%s/prices", id), body, params.IdempotencyKey))
}

// Update an existing price on a plan.
func (r *PlansResource) UpdatePrice(ctx context.Context, id string, priceID string, params *UpdatePlanPriceParams) (*ApiResponse[PlanPrice], error) {
	body := buildBody(map[string]any{
		"price":            params.Price,
		"is_default":       params.IsDefault,
		"trial_days":       params.TrialDays,
		"included_balance": params.IncludedBalance,
		"included_credits": params.IncludedCredits,
		"intro_offer":      params.IntroOffer,
	})
	return parseResponse[PlanPrice](r.http.put(ctx, fmt.Sprintf("/plans/%s/prices/%s", id, priceID), body, params.IdempotencyKey))
}

// Remove a price from a plan.
func (r *PlansResource) DeletePrice(ctx context.Context, id string, priceID string) (*ApiResponse[DeletedObject], error) {
	return parseResponse[DeletedObject](r.http.delete(ctx, fmt.Sprintf("/plans/%s/prices/%s", id, priceID), nil, ""))
}

// Set a specific price as the default for its plan. Unsets previous default.
func (r *PlansResource) SetDefaultPrice(ctx context.Context, id string, priceID string, params *SetDefaultPlanPriceParams) (*ApiResponse[DefaultPlanPrice], error) {
	return parseResponse[DefaultPlanPrice](r.http.put(ctx, fmt.Sprintf("/plans/%s/prices/%s/default", id, priceID), map[string]any{}, params.IdempotencyKey))
}

// Create or update regional currency price overrides for a plan price.
func (r *PlansResource) SetRegionalPrices(ctx context.Context, id string, priceID string, params *UpsertRegionalPricesParams) (*ApiResponse[PlanRegionalPricing], error) {
	body := buildBody(map[string]any{
		"overrides": params.Overrides,
	})
	return parseResponse[PlanRegionalPricing](r.http.put(ctx, fmt.Sprintf("/plans/%s/prices/%s/regional", id, priceID), body, params.IdempotencyKey))
}

// Configure a plan's regional pricing for one currency. Sending only currency and exchangeRate derives every regional value (base price, included balance, feature overage, intro offer) from the USD value at that rate. Optional per-price and per-feature overrides are stored as manual values.
func (r *PlansResource) SetRegionalPricing(ctx context.Context, id string, params *SetPlanRegionalPricingParams) (*ApiResponse[PlanRegionalPricingResult], error) {
	body := buildBody(map[string]any{
		"currency":      params.Currency,
		"exchange_rate": params.ExchangeRate,
		"prices":        params.Prices,
		"features":      params.Features,
		"intro_offers":  params.IntroOffers,
	})
	return parseResponse[PlanRegionalPricingResult](r.http.put(ctx, fmt.Sprintf("/plans/%s/regional", id), body, params.IdempotencyKey))
}

// Remove all regional currency overrides for a plan price.
func (r *PlansResource) DeleteRegionalPrices(ctx context.Context, id string, priceID string) (*ApiResponse[DeletedPlanRegionalPricing], error) {
	return parseResponse[DeletedPlanRegionalPricing](r.http.delete(ctx, fmt.Sprintf("/plans/%s/prices/%s/regional", id, priceID), nil, ""))
}
