// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package commet

import "context"

type AddQuotaParams struct {
	CustomerID     *string `json:"customer_id,omitempty"`
	ExternalID     *string `json:"external_id,omitempty"`
	FeatureCode    string  `json:"feature_code"`
	Count          *int    `json:"count,omitempty"`
	IdempotencyKey string  `json:"-"`
}

type SetQuotaParams struct {
	CustomerID     *string `json:"customer_id,omitempty"`
	ExternalID     *string `json:"external_id,omitempty"`
	FeatureCode    string  `json:"feature_code"`
	Count          int     `json:"count"`
	IdempotencyKey string  `json:"-"`
}

type RemoveQuotaParams struct {
	CustomerID     *string `json:"customer_id,omitempty"`
	ExternalID     *string `json:"external_id,omitempty"`
	FeatureCode    string  `json:"feature_code"`
	Count          *int    `json:"count,omitempty"`
	IdempotencyKey string  `json:"-"`
}

type GetQuotaAllowanceParams struct {
	CustomerID  string `json:"customer_id"`
	FeatureCode string `json:"feature_code"`
}

type GetAllQuotaAllowancesParams struct {
	CustomerID string `json:"customer_id"`
}

type QuotaResource struct {
	http *httpClient
}

// Add to a customer's quota allowance for a feature. Defaults to 1 if count is omitted.
func (r *QuotaResource) Add(ctx context.Context, params *AddQuotaParams) (*ApiResponse[UsageQuotaEvent], error) {
	body := buildBody(map[string]any{
		"customer_id":  params.CustomerID,
		"external_id":  params.ExternalID,
		"feature_code": params.FeatureCode,
		"count":        params.Count,
	})
	return parseResponse[UsageQuotaEvent](r.http.post(ctx, "/usage/quota", body, params.IdempotencyKey))
}

// Set a customer's quota allowance for a feature to an exact value.
func (r *QuotaResource) Set(ctx context.Context, params *SetQuotaParams) (*ApiResponse[UsageQuotaEvent], error) {
	body := buildBody(map[string]any{
		"customer_id":  params.CustomerID,
		"external_id":  params.ExternalID,
		"feature_code": params.FeatureCode,
		"count":        params.Count,
	})
	return parseResponse[UsageQuotaEvent](r.http.put(ctx, "/usage/quota", body, params.IdempotencyKey))
}

// Remove from a customer's quota allowance for a feature. Defaults to 1 if count is omitted. Returns 400 insufficient_balance if the balance would go negative.
func (r *QuotaResource) Remove(ctx context.Context, params *RemoveQuotaParams) (*ApiResponse[UsageQuotaEvent], error) {
	body := buildBody(map[string]any{
		"customer_id":  params.CustomerID,
		"external_id":  params.ExternalID,
		"feature_code": params.FeatureCode,
		"count":        params.Count,
	})
	return parseResponse[UsageQuotaEvent](r.http.delete(ctx, "/usage/quota", body, params.IdempotencyKey))
}

// Get the current quota allowance (used vs included) for a specific feature.
func (r *QuotaResource) Get(ctx context.Context, params *GetQuotaAllowanceParams) (*ApiResponse[UsageQuota], error) {
	query := map[string]string{}
	if params.CustomerID != "" {
		query["customer_id"] = params.CustomerID
	}
	if params.FeatureCode != "" {
		query["feature_code"] = params.FeatureCode
	}
	return parseResponse[UsageQuota](r.http.get(ctx, "/usage/quota", query))
}

// Get all quota allowances for a customer across every quota feature in their plan.
func (r *QuotaResource) GetAll(ctx context.Context, params *GetAllQuotaAllowancesParams) (*ApiResponse[[]UsageQuota], error) {
	query := map[string]string{}
	if params.CustomerID != "" {
		query["customer_id"] = params.CustomerID
	}
	return parseResponse[[]UsageQuota](r.http.get(ctx, "/usage/quota/all", query))
}
